---
services: docker

install:
  - bundle install

script:
  # run kitchen tests (destroy, create, converge, setup, verify and destroy)
  - bundle exec kitchen test

notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      - secure: qj0NDYPxrPt0/Vaz1RMYkEnntXvmbVgYxx4PoiraxhwhFTav8gX1ZZR3d6bOX5gt7/8zctO/SRgR72bt7q52xtatd6akFl0nW1t84XrPYjgChIoiHy2IMIt+IYU6PRTZJbArBUx8eWViISp7srtN00z7talBRdJUdwjShYSqmqdvImm0xIPCwzzXHecn9t0Ecoq4KcVyBt+Mnm/4nClS8q1ZpFG8jI4OCkMlJpXNCdPi06CJMsN8XWOfXB8WWVpDFRZNmWq8snFheDjPLKbdpvCqQxit3t5Lu9NDXt89t1+XH7XoF4n1XcjWyB8FUol3rb9G6atEzQ6lVyEqB3MJQRc/JQn9cfi9G/VqemtTen+VR2Y3zL1TqAjf/0FE+kcCIlT+Yf0Wwr+cZZKXQBQPhmk+V3GduOVpnF8rIztrZJ+PcYc49wt7difkgV5hVvN2ImWmD2SDEQhrjHJPL7l4eED82DdNxUc27DTd8zfII+ZcvrMfcpJPdi/SY9sWiSsuntP9sLrdKawkOwWoYuHy0yFFyE6bfpO1Q7zMd9tPSYxybaBd4DVEb+GZhD3v3qGIsnXelM27R4tp2yy1p73I5wb4wRJchaXP4GaLYxh8rpikvX6veHYHRJ4z66RoWzYgyyb+0/abuMp9TbcgshLS53m3UpDcublEYAZkvmzeiUU=
