---
- name: Upload public certificate
  template:
    src: log-courier.crt
    dest: /etc/log-courier/log-courier.crt

- name: Configure for forwarder
  template:
    src: conf.d/forwarder.conf
    dest: /etc/log-courier/log-courier.conf
  notify: service | log-courier | reloaded
