---
- name: Upload public certificate
  template:
    src: etc/log-courier/ssl.crt
    dest: "{{ log_courier_ssl_certificate_path }}"

- name: Configure for forwarder
  template:
    src: etc/log-courier/log-courier.conf
    dest: /etc/log-courier/log-courier.conf
  notify: service | log-courier | reloaded
