---
- name: Add apt repository
  command: add-apt-repository ppa:devel-k/log-courier

- name: Install Packages | apt
  apt:
    state: latest
    pkg: "{{ item }}"
    update_cache: yes
  with_items:
    - log-courier
