---
- name: Add apt repository
  command: add-apt-repository ppa:devel-k/log-courier

- name: Install Packages | apt
  apt:
    state: latest
    pkg: "{{ item }}"
    update_cache: yes
  with_items:
    - log-courier

- name: Upload public certificate
  template:
    src: log-courier.crt
    dest: /etc/log-courier/log-courier.crt

- name: Configure for forwarder
  template:
    src: conf.d/forwarder.conf
    dest: /etc/log-courier/log-courier.conf
