---
- name: service | log-courier | started
  service:
    state: started
    name: log-courier

- name: service | log-courier | stopped
  service:
    state: stopped
    name: log-courier

- name: service | log-courier | restarted
  service:
    state: restarted
    name: log-courier
